# Generated by Django 5.1.1 on 2024-09-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app_transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
